"""create table

Revision ID: 80967f371ac0
Revises: 
Create Date: 2026-04-15 14:36:10.855280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '80967f371ac0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('destinations', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('destinations', 'country',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('destinations', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('destinations', 'embedding',
               existing_type=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('ix_destinations_id'), table_name='destinations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_destinations_id'), 'destinations', ['id'], unique=False)
    op.alter_column('destinations', 'embedding',
               existing_type=sa.String(),
               type_=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               existing_nullable=True)
    op.alter_column('destinations', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('destinations', 'country',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('destinations', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
